import type { CountryGroup } from '../types/product.types'

export const COUNTRY_GROUPS: CountryGroup[] = [
  {
    label: 'UK',
    emoji: '\u{1F1EC}\u{1F1E7}',
    countries: [
      { name: 'United Kingdom', code: 'GBR', defaultCurrency: 'GBP' },
      { name: 'Isle of Man', code: 'IMN', defaultCurrency: 'GBP' },
      { name: 'Guernsey', code: 'GGY', defaultCurrency: 'GBP' },
      { name: 'Jersey', code: 'JEY', defaultCurrency: 'GBP' },
    ],
  },
  {
    label: 'Europe > Western / Core',
    emoji: '\u{1F1EA}\u{1F1FA}',
    countries: [
      { name: 'France', code: 'FRA', defaultCurrency: 'EUR' },
      { name: 'Germany', code: 'DEU', defaultCurrency: 'EUR' },
      { name: 'Netherlands', code: 'NLD', defaultCurrency: 'EUR' },
      { name: 'Ireland', code: 'IRL', defaultCurrency: 'EUR' },
      { name: 'Austria', code: 'AUT', defaultCurrency: 'EUR' },
      { name: 'Belgium', code: 'BEL', defaultCurrency: 'EUR' },
    ],
  },
  {
    label: 'Europe > Southern',
    emoji: '\u{1F1EA}\u{1F1FA}',
    countries: [
      { name: 'Italy', code: 'ITA', defaultCurrency: 'EUR' },
      { name: 'Spain', code: 'ESP', defaultCurrency: 'EUR' },
      { name: 'Portugal', code: 'PRT', defaultCurrency: 'EUR' },
      { name: 'Greece', code: 'GRC', defaultCurrency: 'EUR' },
    ],
  },
  {
    label: 'Europe > Nordics',
    emoji: '\u{1F1EA}\u{1F1FA}',
    countries: [
      { name: 'Sweden', code: 'SWE', defaultCurrency: 'EUR' },
      { name: 'Denmark', code: 'DNK', defaultCurrency: 'EUR' },
      { name: 'Norway', code: 'NOR', defaultCurrency: 'EUR' },
      { name: 'Finland', code: 'FIN', defaultCurrency: 'EUR' },
      { name: 'Iceland', code: 'ISL', defaultCurrency: 'EUR' },
    ],
  },
  {
    label: 'Europe > Lower / Mixed',
    emoji: '\u{1F1EA}\u{1F1FA}',
    countries: [{ name: 'Poland', code: 'POL', defaultCurrency: 'EUR' }],
  },
  {
    label: 'Europe > Eastern & Balkan',
    emoji: '\u{1F1EA}\u{1F1FA}',
    countries: [
      { name: 'Albania', code: 'ALB', defaultCurrency: 'EUR' },
      { name: 'Andorra', code: 'AND', defaultCurrency: 'EUR' },
      { name: 'Bosnia and Herzegovina', code: 'BIH', defaultCurrency: 'EUR' },
      { name: 'Bulgaria', code: 'BGR', defaultCurrency: 'EUR' },
      { name: 'Croatia', code: 'HRV', defaultCurrency: 'EUR' },
      { name: 'Cyprus', code: 'CYP', defaultCurrency: 'EUR' },
      { name: 'Czech Republic', code: 'CZE', defaultCurrency: 'EUR' },
      { name: 'Estonia', code: 'EST', defaultCurrency: 'EUR' },
      { name: 'Hungary', code: 'HUN', defaultCurrency: 'EUR' },
      { name: 'Latvia', code: 'LVA', defaultCurrency: 'EUR' },
      { name: 'Liechtenstein', code: 'LIE', defaultCurrency: 'EUR' },
      { name: 'Lithuania', code: 'LTU', defaultCurrency: 'EUR' },
      { name: 'Luxembourg', code: 'LUX', defaultCurrency: 'EUR' },
      { name: 'Montenegro', code: 'MNE', defaultCurrency: 'EUR' },
      { name: 'North Macedonia', code: 'MKD', defaultCurrency: 'EUR' },
      { name: 'Romania', code: 'ROU', defaultCurrency: 'EUR' },
      { name: 'San Marino', code: 'SMR', defaultCurrency: 'EUR' },
      { name: 'Serbia', code: 'SRB', defaultCurrency: 'EUR' },
      { name: 'Slovakia', code: 'SVK', defaultCurrency: 'EUR' },
      { name: 'Slovenia', code: 'SVN', defaultCurrency: 'EUR' },
      { name: 'Malta', code: 'MLT', defaultCurrency: 'EUR' },
    ],
  },
  {
    label: 'Europe > Territories',
    emoji: '\u{1F1EA}\u{1F1FA}',
    countries: [
      { name: 'Aland Islands', code: 'ALA', defaultCurrency: 'EUR' },
      { name: 'Faroe Islands', code: 'FRO', defaultCurrency: 'EUR' },
      { name: 'Monaco', code: 'MCO', defaultCurrency: 'EUR' },
      { name: 'Switzerland', code: 'CHE', defaultCurrency: 'EUR' },
    ],
  },
  {
    label: 'Japan',
    emoji: '\u{1F1EF}\u{1F1F5}',
    countries: [{ name: 'Japan', code: 'JPN', defaultCurrency: 'JPY' }],
  },
  {
    label: 'Canada',
    emoji: '\u{1F1E8}\u{1F1E6}',
    countries: [{ name: 'Canada', code: 'CAN', defaultCurrency: 'CAD' }],
  },
  {
    label: 'Australia',
    emoji: '\u{1F1E6}\u{1F1FA}',
    countries: [{ name: 'Australia', code: 'AUS', defaultCurrency: 'AUD' }],
  },
  {
    label: 'South Korea',
    emoji: '\u{1F1F0}\u{1F1F7}',
    countries: [{ name: 'South Korea', code: 'KOR', defaultCurrency: 'KRW' }],
  },
  {
    label: 'Latin America',
    emoji: '\u{1F30E}',
    countries: [
      { name: 'Brazil', code: 'BRA', defaultCurrency: 'BRL' },
      { name: 'Mexico', code: 'MEX', defaultCurrency: 'MXN' },
      { name: 'Chile', code: 'CHL', defaultCurrency: 'CLP' },
      { name: 'Peru', code: 'PER', defaultCurrency: 'PEN' },
      { name: 'Argentina', code: 'ARG', defaultCurrency: 'USD' },
      { name: 'Colombia', code: 'COL', defaultCurrency: 'USD' },
      { name: 'Costa Rica', code: 'CRI', defaultCurrency: 'USD' },
      { name: 'Uruguay', code: 'URY', defaultCurrency: 'USD' },
      { name: 'Ecuador', code: 'ECU', defaultCurrency: 'USD' },
      { name: 'Panama', code: 'PAN', defaultCurrency: 'USD' },
      { name: 'Paraguay', code: 'PRY', defaultCurrency: 'USD' },
      { name: 'Guatemala', code: 'GTM', defaultCurrency: 'USD' },
    ],
  },
  {
    label: 'Other',
    emoji: '\u{1F30D}',
    countries: [
      { name: 'India', code: 'IND', defaultCurrency: 'INR' },
      { name: 'Philippines', code: 'PHL', defaultCurrency: 'USD' },
      { name: 'United Arab Emirates', code: 'ARE', defaultCurrency: 'USD' },
      { name: 'Israel', code: 'ISR', defaultCurrency: 'USD' },
      { name: 'Saudi Arabia', code: 'SAU', defaultCurrency: 'USD' },
      { name: 'South Africa', code: 'ZAF', defaultCurrency: 'USD' },
      { name: 'New Zealand', code: 'NZL', defaultCurrency: 'USD' },
    ],
  },
]
